### ISSUE TITLE
Missing play controls

### ISSUE THREAD

**Issue by jonfre** [XilinJia/Podcini#104]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/Podcini/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/podcini/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

6.11.4

### Where did you get the app from

F-Droid

### Android version

GrapheneOS

### Steps to reproduce

1. Open queue with some items
2. Start playback
3. Press phone back button
5. Start app again

### Expected behaviour

Queue shows with play controls at bottom

### Current behaviour

No play controls at bottom.

**Comment by XilinJia** [comment]
Thanks for the note.

As I tested with 6.11.7, set default page to "remember last" (since you want the queue to open on the next start), when I do:

- Open queue with some items
- Start playback
- Press phone back button

The play continues. to restart the app, I need to kick it out, and then start it. When it starts, it opens the Queues view with the playerUI at the bottom.

Now, this is not always the case, say you set the default page to Subscriptions, where the playerUI doesn't seem to appear.

I'm not quite certain what should be the right behavior with this operation in all sort of scenarios.  Welcome any suggestions.

**Comment by jonfre** [comment]
Ok, I had the queue as default. I get the same result (no controls) with "remember last" and other view.

I think the controls should always be visible if something is playing or paused.

**Comment by XilinJia** [comment]
should be fixed in 6.12.0

**Comment by XilinJia** [comment]
Any updates on this?

**Comment by jonfre** [comment]
Yes now it works
