### ISSUE TITLE
GPLv3 license violation

### ISSUE THREAD

**Issue by rottenwheel** [XilinJia/Podcini#2]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

3.2.5

### Where did you get the app from

Other

### Android version

14

### Expected behaviour

Interesting initiative and the description in the README is promising. However, I think @XilinJia is messing with the license. A cursory look tells me he wants to preserve original AntennaPod's GPLv3 license while licensing his modifications and additions as MIT, which is incongruent. I am not a lawyer but as far as I can tell, once a piece of code is GPLv3, all its next iterations must respect such license to the letter, that is, keep it under GPLv3. 

Paging @loucasal, @AntennaPod.

**Comment by XilinJia** [comment]
where did you see that I license my modifications and additions as MIT?  This whole project is marked as with GPLv3.

**Comment by XilinJia** [comment]
The LICENSE file was copied from the forked project, and it has the paragraphs on "Parts of AntennaPod use the MIT license".  Since I can't be sure which parts of the project uses the MIT license, I don't want to delete those paragraphs.

**Comment by ByteHamster** [comment]
What definitely is a license violation is the fact that the name in the MIT part of the license got changed from "AntennaPod contributors" to "Podcini contributors". I assume this happened because of search-and-replace and is not a conscious violation.

(That MIT part is there because AntennaPod switched from MIT to GPL at some point. This is a one-way switch - once it's GPL, there is no way to go back unless every single contributor agrees. Still, that MIT part needs to stay somewhere to comply with the old license)

**Comment by XilinJia** [comment]
@ByteHamster thanks for pointing this out.  Sorry for the error.  I just changed it back to AntennaPod contributors.

**Comment by firefoxlover** [comment]
This seems to be fixed, the error is not there anymore. Is everything GPLv3?
