### ISSUE TITLE
Issues with Playing from Notification/ Bluetooth/Widget

### ISSUE THREAD

**Issue by ghost** [XilinJia/Podcini#43]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

4.9.6

### Where did you get the app from

Google Play

### Android version

14

### Device model

Pixel 7 Pro

### Steps to reproduce

(1) Play/resume podcast from either Bluetooth or from a notification or from a homescreen widget
(2) Open the app

### Expected behaviour

The app should show the same playing status and podcast position.
AND
Pressing the forward/back button should have the effect chosen in Settings -> Playback
AND
Upon pause the podcast position should be saved in the app

### Current behaviour

The app shows no podcast is playing
AND
Hardware forward button always skips episode, back button always restarts it. Chosen settings for Rewind/Fast forward settings are not honoured.
AND
Upon going back to the app, resuming playback results in weird behaviour. Sometimes the podcasts resumes from the position paused from the previous playback, other times it resumes from the position shown in the app, regardless of where it was actually last paused.

Possibly related to #37

**Comment by XilinJia** [comment]
The mismatch of play/pause button is fixed in the next release.

The hardware rewind and forward buttons might be tied to the two buttons next to play/pause.  Currently there is something strange with the positioning of the buttons as I described in the related issue.  Will need further investigation.

If you play/resume/rewind/forward an episode from the notification and come to the app, the position is not updated in your version.  This relates to the mismatch of play/pause button issue and is fixed in the coming release.  Actually before the fix, if you press the play/pause button on the player to get it in sync with the play status, the position is set correctly.  BTW, Podicini is only updates positions every 5 second to conserve energy.

**Comment by rrd1** [comment]
I can confirm that rewind/forward is not working as expected when triggered via Bluetooth device. Tried headphones (Goggle Pixel Buds Pro) and car audio. Same functionality works fine with same devices but original Antennapod.

Phone: Pixel 7, Android 14
Forward (30s) expected, nothing happens when triggered via BT
Backward (10s) expected, restarts the episode from beginning when triggered via BT

Let me know if you need further information to investigate the issue.

**Comment by XilinJia** [comment]
The buttons issue should have been fixed in 5.4.1.  let me know.

**Comment by rrd1** [comment]
Thanks a lot for your fast reaction, really appreciated! Forward and rewind works now for me with both BT devices.
Thanks a lot again!

**Comment by XilinJia** [comment]
Glad it works out well.  Cheers

**Comment by XilinJia** [comment]
Not sure if this old issue is still relevant.  Closing, but feel free to re-open with new evidence.
