### ISSUE TITLE
Filter queue by tag - or multiple queues

### ISSUE THREAD

**Issue by dyeray** [XilinJia/Podcini#56]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same feature request.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [X] I will describe the problem with as much detail as possible.
- [X] This request contains only one single feature, **not** a list of multiple (related) features.

### App version

5.4.2

### Where did you get the app from

F-Droid

### Problem you may be having, or feature you want

App currently has no support for multiple queues, in order to play different type of shows depending on needs (i.e. a queue for videos, a queue for shows in one specific language, a queue for kids friendly content).

A suggestion for implementing a basic version of this would be using the already existing feature of tags. Same way as Subscriptions section can be filtered by tags, queue could also be filtered by tags, and episodes played would only be selected from the currently selected tag.

Related feature requests for multiple queues in AntennaPod: https://github.com/AntennaPod/AntennaPod/issues/2648

**Comment by XilinJia** [comment]
Thanks for the suggestion.

Podcini 6 (to be released soon) is re-structured to natively support multiple queues.

**Comment by XilinJia** [comment]
try it out in 6.0.3, though still in pre-release, it's getting close to a full release.

**Comment by ehula** [comment]
I have a question about these multiple queues. Can they be populated automatically? For instance, I would like the ability to select a few of my subscribed podcasts to have their episodes automatically added to a queue. Is this the idea behind multiple queues?

**Comment by XilinJia** [comment]
Currently every action (automatic or manual) of "add to queue" adds the episodes to the current/active queue, in the same way as before.  The only difference is that before adding to queue, you can set a current/active queue.

In the sense of automatically having podcasts on separate queues, I have plan for the next couple releases to have a "virtual" queue, such that when you play an episode from a podcast list (rather than from a queue), a virtual queue will be set as current that contains only the episodes from the current podcast (subscription), so the next episode to play is one from the current podcast.

**Comment by dyeray** [comment]
My 2 cents, not wanting to bash, just giving my feedback after testing it, since it is still pretty new.

First, switching the active queue is a bit cumbersome, as it requires many clicks. Second, it would be great to be able to define dynamically the queues available, with its own name (by default there would only be one).

Each podcast on the settings page should be able to be linked to a queue, so when downloaded, the episodes of such podcast would go to that specific queue, and not the active one.

Why? I think multiple queues are usually used for podcasts that are listened at different times. For example podcasts in English go to a queue, podcasts that are kids safe go to a different queue, etc. This is usually related to the podcast, so there should be no need to do this classification manually every time the podcast is downloaded.

Regards, and thanks for your work.

**Comment by ehula** [comment]
Would you consider adding functionality something like "smart queues"?

Here is what I would like to be able to do. I would like to select a particular set of podcasts whereby their new episodes automatically get added to a particular queue. For example, I would like a "daily news" queue, a "technology" queue, a "business" queue, etc. Each of those queues would automatically populate with the latest episodes of the podcasts I choose for each. And since I don't download episodes, I would like this to work with streamed episodes (as well as downloaded episodes.)

I currently don't see any way to automatically add episodes to a queue. Maybe it only works with downloaded episodes, which I don't use.

Thanks for your consideration.

**Comment by XilinJia** [comment]
> switching the active queue is a bit cumbersome

Why is that? From any view with an episode list, there is a menu item allowing you to switch queue.  After that, you use the active queue.

Sure, it's not designed for the ease of constant switching queues (I don't see why anyone wants to do that).

**Comment by XilinJia** [comment]
@ehula perhaps not really a "smart queue", but adding a feed preference of "Associated queue" can be fairly simple.  So once a feed is set with an associated queue, all episodes from that feed would go to the queue.

**Comment by XilinJia** [comment]
> Each podcast on the settings page should be able to be linked to a queue, so when downloaded, the episodes of such podcast would go to that specific queue, and not the active one.

Creating a separate queue for each feed sounds like an overkill.  But I mentioned my plan to have a "virtual" queue: https://github.com/XilinJia/Podcini/issues/56#issuecomment-2202207707

**Comment by dyeray** [comment]
> Sure, it's not designed for the ease of constant switching queues (I don't see why anyone wants to do that).

This is only needed if there is no link between a podcast and the queue it belongs to. Imagine a user has 4 queues (one for videos, one for regular podcasts, one for podcasts in foreign languages, and one kids friendly). This means, the moment I want to refresh feeds and download the new stuff to populate those feeds, I have to at least go to the queue, switch the active queue (with 3 clicks), go again to the inbox, download the episods of first queue, then go to the queue again, switch, go back to inbox, download the episodes for the 2nd queue, and so on.

The moment that there is a setting to link a podcast to a queue, then above constant switch of queues is not needed. I think this also answers:

> Creating a separate queue for each feed sounds like an overkill. But I mentioned my plan to have a "virtual" queue: https://github.com/XilinJia/Podcini/issues/56#issuecomment-2202207707

I'm not saying each podcast is linked to its own queue. I'm saying I should be able to link through the settings a specific podcast to an existing queue, same way a podcast can be linked to a specific tag. This means, maybe I have 20 podcasts linked to the videos queue, 10 to the foreign-language queue, etc.

**Comment by XilinJia** [comment]
I think the fundamental question to ask to why we need to put something onto a queue and then play it from the queue.  The only purpose is that we need some kind of sequence for the playing.  Unless one needs to mix some episodes from different feeds, there is no real need for a queue (let alone multiple queues) because the episode list of a feed serves as a natural queue and we can simply play the episodes off from that list.  That's my thought for a "virtual" queue.

**Comment by ehula** [comment]
> @ehula perhaps not really a "smart queue", but adding a feed preference of "Associated queue" can be fairly simple. So once a feed is set with an associated queue, all episodes from that feed would go to the queue.

Not quite. I would only want all **new** episodes to be added to the associated queue when the feed gets updated. Maybe that is what you meant?

To make this more useful, it would be nice to be able to rename queues.

**Comment by ehula** [comment]
In fact, you can combine my ideas with the ideas of @dyeray with a new setting in 'Podcast settings' called Queue:
```
Queue

[                             + ]
(episodes you "Add to queue" will go here)

[ X ] Automatically add new episodes to this queue
```
Then, to improve the flow, on the Queue page, turn the title (i.e. "Queue: Default") into a drop-down list to allow a user to quickly change to a different queue.

You may want to change "Queue" in the Navigation Drawer to "Queues".

**Comment by XilinJia** [comment]
in 6.2.0, queues now can be renamed, added (up to 10), and associated to any feed.
