### ISSUE TITLE
F-Droid release of Podcini 6

### ISSUE THREAD

**Issue by linsui** [XilinJia/Podcini#59]
Since the appid is chagned, we need to add the new version as a new app. Are you going to retire Podcini 5 and publish 6 on F-Droid? What's your plan?

**Comment by XilinJia** [comment]
Thanks for the note.
Yes, as previously discusses via email, I would like Podcini 6 as new app on f-droid since it's incompatible with 5.  I don't want to remove 5 from f-droid just yet, perhaps later.
6.0.0 is currently a pre-release.  After some testing, I look to push a full release of 6.0.1.  Should I apply to f-droid for the new app only after then?  I understand I need to prepare a new yaml file.

**Comment by linsui** [comment]
Oh, right, we discussed that in https://gitlab.com/fdroid/rfp/-/issues/2679. You can add the new app anytime when you feel it's ready. :)
