### ISSUE TITLE
Use /android/media instead of /android/data for downloads

### ISSUE THREAD

**Issue by fabiocosta0305** [XilinJia/Podcini#70]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same feature request.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [X] I will describe the problem with as much detail as possible.
- [X] This request contains only one single feature, **not** a list of multiple (related) features.

### App version

6.0.13

### Where did you get the app from

F-Droid

### Problem you may be having, or feature you want

It would be nicer to save downloaded podcast files under /android/media instead of /android/data... This would turn more manageable to backup files if needed

**Comment by XilinJia** [comment]
Thanks for reporting.
Will check about using /android/media.
But regardless, for backing up media files, you can export them from 6.0.13 to any folder you like, and then re-import them when needed.

**Comment by XilinJia** [comment]
Using /android/media appears not a good option.
1) when app is uninstalled, the files are left behind as junk
2) it creates an illusion for the user that media files can simply be copied into the folder and Podcini will play them.  Actually, Podcini needs to go through processes to match any media file with existing subscription and episode, otherwise, the media files are useless. That's what the media files import routine is for.
3) though one can freely back up media files from /android/media, for the same reason above, to restore them, one would still have to use the import routine, so it serves no advantage over simply exporting from Podcini.

Anyhow, any counter arguments are welcome.
